version: "3.9"

services:
  mysql-server:
    image: mysql:8.0.38
    container_name: zabbix-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: zabbix
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
    command: --log-bin-trust-function-creators=1
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      redecezar:
        ipv4_address: 172.20.0.2
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-7.4-latest
    container_name: zabbix-server
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: mysql-server
      DB_SERVER_ROOT_PASSWORD: zabbix
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
    ports:
      - "10051:10051"
    depends_on:
      mysql-server:
        condition: service_healthy
    volumes:
      - zabbix_alertscripts:/usr/lib/zabbix/alertscripts
      - zabbix_export:/var/lib/zabbix/export
    networks:
      redecezar:
        ipv4_address: 172.20.0.3

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-7.4-latest
    container_name: zabbix-web
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: mysql-server
      DB_SERVER_ROOT_PASSWORD: zabbix
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: America/Cuiaba
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      zabbix-server:
        condition: service_started
    networks:
      redecezar:
        ipv4_address: 172.20.0.4

  zabbix-agent2:
    image: zabbix/zabbix-agent2:alpine-7.4-latest
    container_name: zabbix-agent2
    restart: unless-stopped
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_HOSTNAME: "Docker Host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zabbix-server
    networks:
      redecezar:
        ipv4_address: 172.20.0.5

  Docker01:
    image: zabbix/zabbix-agent2:alpine-7.4-latest
    container_name: Docker01
    restart: unless-stopped
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_HOSTNAME: Docker01
    depends_on:
      - zabbix-server
    networks:
      redecezar:
        ipv4_address: 172.20.0.6

  Docker02:
    image: zabbix/zabbix-agent2:alpine-7.4-latest
    container_name: Docker02
    restart: unless-stopped
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_HOSTNAME: Docker02
    depends_on:
      - zabbix-server
    networks:
      redecezar:
        ipv4_address: 172.20.0.7

networks:
  redecezar:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

volumes:
  mysql_data:
  zabbix_alertscripts:
  zabbix_export:




#como executar um docker compose:

#Subir o Docker:
#docker compose up -d

#Derrubar o Docker:
#docker compose down -v


#http://localhost:8080


#Usu√°rio: Admin
#Senha: zabbix





